### ISSUE TITLE
Karaf not starting properly

### ISSUE THREAD

**Issue by HiromuHota** [HiromuHota/pentaho-kettle#12]
Related to #10, I've been trying to launch Karaf.
As described in [here](https://github.com/HiromuHota/pentaho-kettle/wiki/OSGi), I am able to launch Karaf by adding PDI-OSGI-Bridge and related dependencies, but errors happen within Karaf.

This was the message when I first launched Karaf from webSpoon.
```
11:13:51,194 INFO  [KarafInstance] 
*******************************************************************************
*** Karaf Instance Number: 5 at /Users/hiromu/workspace/webspoon/ui/./syste ***
***   m/karaf/caches/basicapplication/data-1                                ***
*** Karaf Port:8806                                                         ***
*** OSGI Service Port:9055                                                  ***
*******************************************************************************
11:13:51,195 INFO  [KarafBoot] Checking to see if org.pentaho.clean.karaf.cache is enabled
Dec 13, 2016 11:13:51 AM org.apache.karaf.main.Main launch
INFO: Installing and starting initial bundles
Dec 13, 2016 11:13:51 AM org.apache.karaf.main.Main launch
INFO: All initial bundles installed and set to start
Dec 13, 2016 11:13:52 AM org.apache.karaf.main.Main$KarafLockCallback lockAquired
INFO: Lock acquired. Setting startlevel to 100
Creating configuration from jmx.acl.org.apache.karaf.bundle.cfg
Creating configuration from org.apache.karaf.command.acl.config.cfg
Creating configuration from pentaho.marketplace.di.cfg
Creating configuration from jmx.acl.osgi.compendium.cm.cfg
Creating configuration from org.apache.karaf.features.repos.cfg
Creating configuration from org.ops4j.pax.logging.cfg
Creating configuration from mondrian.cfg
Creating configuration from org.apache.karaf.jaas.cfg
Creating configuration from org.apache.karaf.command.acl.kar.cfg
Creating configuration from jmx.acl.org.apache.karaf.config.cfg
Creating configuration from org.apache.karaf.kar.cfg
Creating configuration from pentaho.geo.roles.cfg
Creating configuration from org.apache.karaf.shell.cfg
Creating configuration from org.apache.karaf.webconsole.cfg
Creating configuration from org.apache.karaf.features.cfg
Creating configuration from jmx.acl.java.lang.Memory.cfg
Creating configuration from org.apache.karaf.command.acl.scope_bundle.cfg
Creating configuration from org.apache.karaf.log.cfg
Creating configuration from org.apache.karaf.command.acl.shell.cfg
Creating configuration from org.apache.karaf.command.acl.bundle.cfg
Creating configuration from org.ops4j.pax.url.mvn.cfg
Creating configuration from org.pentaho.caching-default.cfg
Creating configuration from org.apache.karaf.features.obr.cfg
Creating configuration from org.ops4j.pax.web.cfg
Creating configuration from org.apache.karaf.command.acl.feature.cfg
Creating configuration from org.apache.activemq.server-default.cfg
Creating configuration from org.apache.karaf.command.acl.jaas.cfg
Creating configuration from jmx.acl.org.apache.karaf.security.jmx.cfg
Creating configuration from org.apache.activemq.webconsole.cfg
Creating configuration from org.apache.karaf.command.acl.system.cfg
Creating configuration from pentaho.metaverse.cfg
Creating configuration from jmx.acl.cfg
Creating configuration from org.apache.karaf.management.cfg
Creating configuration from org.apache.felix.fileinstall-deploy.cfg
Creating configuration from org.pentaho.features.cfg
Dec 13, 2016 11:13:55 AM org.pentaho.caching.impl.PentahoCacheManagerFactory$RegistrationHandler$1 onSuccess
INFO: New Caching Service registered
11:15:32,393 ERROR [KarafLifecycleListener] The Kettle Karaf Lifecycle Listener failed to execute properly after waiting for 100 seconds. Releasing lifecycle hold, but some services may be unavailable.
```

This was another message on the 2nd run.
```
11:16:19,074 INFO  [KarafInstance] 
*******************************************************************************
*** Karaf Instance Number: 5 at /Users/hiromu/workspace/webspoon/ui/./syste ***
***   m/karaf/caches/basicapplication/data-1                                ***
*** Karaf Port:8806                                                         ***
*** OSGI Service Port:9055                                                  ***
*******************************************************************************
11:16:19,074 INFO  [KarafBoot] Checking to see if org.pentaho.clean.karaf.cache is enabled
Dec 13, 2016 11:16:19 AM org.apache.karaf.main.Main$KarafLockCallback lockAquired
INFO: Lock acquired. Setting startlevel to 100
Dec 13, 2016 11:16:21 AM org.pentaho.caching.impl.PentahoCacheManagerFactory$RegistrationHandler$1 onSuccess
INFO: New Caching Service registered
ERROR: Bundle pdi-dataservice-server-plugin [59] Error starting mvn:pentaho/pdi-dataservice-server-plugin/6.1.0.1-196 (org.osgi.framework.BundleException: Unresolved constraint in bundle pdi-dataservice-server-plugin [59]: Unable to resolve 59.0: missing requirement [59.0] osgi.wiring.package; (&(osgi.wiring.package=org.pentaho.di.trans.steps.mongodbinput)(version>=6.1.0)(!(version>=7.0.0))) [caused by: Unable to resolve 65.0: missing requirement [65.0] osgi.wiring.package; (osgi.wiring.package=org.pentaho.di.ui.core)])org.osgi.framework.BundleException: Unresolved constraint in bundle pdi-dataservice-server-plugin [59]: Unable to resolve 59.0: missing requirement [59.0] osgi.wiring.package; (&(osgi.wiring.package=org.pentaho.di.trans.steps.mongodbinput)(version>=6.1.0)(!(version>=7.0.0))) [caused by: Unable to resolve 65.0: missing requirement [65.0] osgi.wiring.package; (osgi.wiring.package=org.pentaho.di.ui.core)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.lang.Thread.run(Thread.java:745)

11:18:00,009 ERROR [KarafLifecycleListener] The Kettle Karaf Lifecycle Listener failed to execute properly after waiting for 100 seconds. Releasing lifecycle hold, but some services may be unavailable.
```

**Comment by HiromuHota** [comment]
Solved by editing `system/karaf/etc/org.apache.karaf.features.cfg` as
```
#featuresBoot=config,pentaho-client,pentaho-metaverse,pdi-dataservice,pdi-data-refinery
featuresBoot=config,pentaho-client-minimal
```
and `system/karaf/system/pentaho/pentaho-karaf-features/6.1.0.1-196/pentaho-karaf-features-6.1.0.1-196-standard.xml` as
```
  <feature name="pentaho-client-minimal" version="1.0">
    <feature>pentaho-base</feature>
    <!--<bundle>mvn:pentaho/pentaho-mongo-utils/6.1.0.1-196</bundle>-->
    <!--<bundle>wrap:mvn:pentaho/pentaho-mongodb-plugin/6.1.0.1-196</bundle>-->
    <!--<bundle>mvn:org.mongodb/mongo-java-driver/2.13.0</bundle>-->
    <bundle>mvn:pentaho/pdi-osgi-bridge-activator/6.1.0.1-196</bundle>
   <bundle>mvn:commons-collections/commons-collections/3.2.2</bundle>
  </feature>
```

It has been confirmed that webSpoon users can now see the marketplace and install plugins from there.
However, this is not a real fix because it disables some features/bundles.
I will close this issue for now and will restore the disabled features/bundles in the future.

**Comment by HiromuHota** [comment]
I explained how to prepare system/karaf folder in the webspoon-6.1_karaf branch.
