### ISSUE TITLE
Error closing Spoon when a session expires

### ISSUE THREAD

**Issue by HiromuHota** [HiromuHota/pentaho-kettle#144]
## Expected Behavior

`Spoon.getInstance().quitFile( false );` should be gracefully executed.

## Actual Behavior
Screenshots and error messages are helpful.

```
2019/01/25 20:02:10 - Spoon - Spoon
2019/01/25 20:33:13 - General - ERROR (version 8.2.0.0-342-18, build 8.2.0.0-342-18 from 2019-01-21 04.17.10 by jenkins) : Error closing Spoon
2019/01/25 20:33:13 - General - ERROR (version 8.2.0.0-342-18, build 8.2.0.0-342-18 from 2019-01-21 04.17.10 by jenkins) : java.lang.RuntimeException: Already disposed
2019/01/25 20:33:13 - General - 	at org.pentaho.di.core.SwtUniversalImage.checkDisposed(SwtUniversalImage.java:64)
2019/01/25 20:33:13 - General - 	at org.pentaho.di.core.SwtUniversalImage.getAsBitmapForSize(SwtUniversalImage.java:88)
2019/01/25 20:33:13 - General - 	at org.pentaho.di.ui.core.gui.GUIResource.getImageStartMedium(GUIResource.java:2014)
2019/01/25 20:33:13 - General - 	at org.pentaho.di.ui.spoon.tree.provider.JobEntriesFolderProvider.refresh(JobEntriesFolderProvider.java:59)
2019/01/25 20:33:13 - General - 	at org.pentaho.di.ui.spoon.tree.provider.AutomaticTreeFolderProvider.checkUpdate(AutomaticTreeFolderProvider.java:37)
2019/01/25 20:33:13 - General - 	at org.pentaho.di.ui.spoon.tree.RootNode.checkUpdate(RootNode.java:73)
2019/01/25 20:33:13 - General - 	at org.pentaho.di.ui.spoon.tree.TreeManager.checkUpdate(TreeManager.java:110)
2019/01/25 20:33:13 - General - 	at org.pentaho.di.ui.spoon.Spoon.showMetaTree(Spoon.java:6340)
2019/01/25 20:33:13 - General - 	at org.pentaho.di.ui.spoon.Spoon.refreshTree(Spoon.java:6323)
2019/01/25 20:33:13 - General - 	at org.pentaho.di.ui.spoon.delegates.SpoonTabsDelegate.tabSelected(SpoonTabsDelegate.java:507)
2019/01/25 20:33:13 - General - 	at org.pentaho.di.ui.spoon.Spoon.tabSelected(Spoon.java:3412)
2019/01/25 20:33:13 - General - 	at org.pentaho.xul.swt.tab.TabSet.notifySelectListeners(TabSet.java:135)
2019/01/25 20:33:13 - General - 	at org.pentaho.xul.swt.tab.TabSet.setSelected(TabSet.java:237)
2019/01/25 20:33:13 - General - 	at org.pentaho.xul.swt.tab.TabSet.setSelected(TabSet.java:244)
2019/01/25 20:33:13 - General - 	at org.pentaho.di.ui.spoon.Spoon.quitFile(Spoon.java:5054)
2019/01/25 20:33:13 - General - 	at org.pentaho.di.ui.spoon.WebSpoonEntryPoint.lambda$createContents$275488fb$1(WebSpoonEntryPoint.java:120)
2019/01/25 20:33:13 - General - 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
2019/01/25 20:33:13 - General - 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:664)
2019/01/25 20:33:13 - General - 	at org.eclipse.swt.widgets.Display.sendDisposeEvent(Display.java:755)
2019/01/25 20:33:13 - General - 	at org.eclipse.swt.widgets.Display.release(Display.java:738)
2019/01/25 20:33:13 - General - 	at org.eclipse.swt.graphics.Device.dispose(Device.java:279)
2019/01/25 20:33:13 - General - 	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.processShutdown(UIThread.java:179)
2019/01/25 20:33:13 - General - 	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:309)
2019/01/25 20:33:13 - General - 	at java.lang.Thread.run(Thread.java:748)
2019/01/25 20:33:13 - General - 	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
```

## Steps to Reproduce the Problem

  1. Be inactive for 30 minutes or more without closing a Browser window/tab.

### Server
  - webSpoon: 0.8.2.18

**Comment by fantasyWJP** [comment]
does this issue solved?  i encountered the same question~

**Comment by luoyuwei3919** [comment]
Is there a solution to this problem? I have the same problem. @HiromuHota
