### ISSUE TITLE
Folder tree cannot expanded beyond child folders

### ISSUE THREAD

**Issue by HiromuHota** [HiromuHota/pentaho-kettle#146]
## Expected Behavior

<img width="802" alt="screen shot 2019-01-29 at 9 00 27 am" src="https://user-images.githubusercontent.com/20668349/51925653-635a9400-23a4-11e9-9562-75c3ba42cbd2.png">

## Actual Behavior

![image](https://user-images.githubusercontent.com/20668349/51925265-88023c00-23a3-11e9-98cd-608961250030.png)

![image](https://user-images.githubusercontent.com/20668349/51925310-9d776600-23a3-11e9-8089-3613bd086ccc.png)

```
Ignored reentrant call while viewer is busy. This is only logged once per viewer instance, but similar calls will still be ignored.
java.lang.RuntimeException
	at org.eclipse.jface.viewers.ColumnViewer.checkBusy(ColumnViewer.java:759)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setExpandedState(AbstractTreeViewer.java:2435)
	at org.pentaho.ui.xul.swt.tags.SwtTree.setTreeItemExpanded(SwtTree.java:1836)
	at org.pentaho.ui.xul.swt.tags.SwtTreeItem.setExpanded(SwtTreeItem.java:187)
	at org.pentaho.ui.xul.swt.tags.SwtTree$6.treeExpanded(SwtTree.java:375)
	at org.eclipse.jface.viewers.AbstractTreeViewer$3.run(AbstractTreeViewer.java:1105)
	at org.eclipse.jface.util.SafeRunnable$1.run(SafeRunnable.java:130)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:177)
	at org.eclipse.jface.viewers.AbstractTreeViewer.fireTreeExpanded(AbstractTreeViewer.java:1103)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleTreeExpand(AbstractTreeViewer.java:1450)
	at org.eclipse.jface.viewers.TreeViewer.handleTreeExpand(TreeViewer.java:952)
	at org.eclipse.jface.viewers.AbstractTreeViewer$4.treeExpanded(AbstractTreeViewer.java:1459)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:161)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:869)
	at org.eclipse.jface.window.Window.open(Window.java:845)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:80)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:47)
	at org.pentaho.di.ui.repository.repositoryexplorer.RepositoryExplorer.show(RepositoryExplorer.java:146)
	at org.pentaho.di.ui.spoon.Spoon$26$1.run(Spoon.java:4146)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:193)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1201)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
Ignored reentrant call while viewer is busy. This is only logged once per viewer instance, but similar calls will still be ignored.
java.lang.RuntimeException
	at org.eclipse.jface.viewers.ColumnViewer.checkBusy(ColumnViewer.java:759)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setExpandedState(AbstractTreeViewer.java:2435)
	at org.pentaho.ui.xul.swt.tags.SwtTree.setTreeItemExpanded(SwtTree.java:1836)
	at org.pentaho.ui.xul.swt.tags.SwtTreeItem.setExpanded(SwtTreeItem.java:187)
	at org.pentaho.ui.xul.swt.tags.SwtTree$6.treeExpanded(SwtTree.java:375)
	at org.eclipse.jface.viewers.AbstractTreeViewer$3.run(AbstractTreeViewer.java:1105)
	at org.eclipse.jface.util.SafeRunnable$1.run(SafeRunnable.java:130)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:177)
	at org.eclipse.jface.viewers.AbstractTreeViewer.fireTreeExpanded(AbstractTreeViewer.java:1103)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleTreeExpand(AbstractTreeViewer.java:1450)
	at org.eclipse.jface.viewers.TreeViewer.handleTreeExpand(TreeViewer.java:952)
	at org.eclipse.jface.viewers.AbstractTreeViewer$4.treeExpanded(AbstractTreeViewer.java:1459)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:161)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:869)
	at org.eclipse.jface.window.Window.open(Window.java:845)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:80)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:47)
	at org.pentaho.di.ui.repository.repositoryexplorer.RepositoryExplorer.show(RepositoryExplorer.java:146)
	at org.pentaho.di.ui.spoon.Spoon$26$1.run(Spoon.java:4146)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:193)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1201)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
Exception occurred
org.pentaho.ui.xul.binding.BindingException: Error invoking setter method [setSelectedFolderItems] on target: org.pentaho.di.ui.repository.repositoryexplorer.controllers.BrowseController@338be58e
	at org.pentaho.ui.xul.swt.SwtBinding$1.propertyChange(SwtBinding.java:128)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at org.pentaho.ui.xul.swt.tags.SwtTree$8.selectionChanged(SwtTree.java:439)
	at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:166)
	at org.eclipse.jface.util.SafeRunnable$1.run(SafeRunnable.java:130)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:177)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:164)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2193)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1216)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1246)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:232)
	at org.eclipse.jface.util.OpenStrategy.access$3(OpenStrategy.java:226)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:403)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:869)
	at org.eclipse.jface.window.Window.open(Window.java:845)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:80)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:47)
	at org.pentaho.di.ui.repository.repositoryexplorer.RepositoryExplorer.show(RepositoryExplorer.java:146)
	at org.pentaho.di.ui.spoon.Spoon$26$1.run(Spoon.java:4146)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:193)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1201)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.ui.xul.swt.SwtBinding$1.propertyChange(SwtBinding.java:124)
	... 37 more
Caused by: java.lang.NullPointerException
	at org.pentaho.di.ui.repository.repositoryexplorer.controllers.BrowseController.setSelectedFolderItems(BrowseController.java:800)
	... 41 more
Exception occurred
org.pentaho.ui.xul.binding.BindingException: Error invoking setter method [setSelectedFolderItems] on target: org.pentaho.di.ui.repository.repositoryexplorer.controllers.BrowseController@338be58e
	at org.pentaho.ui.xul.swt.SwtBinding$1.propertyChange(SwtBinding.java:128)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at org.pentaho.ui.xul.swt.tags.SwtTree$8.selectionChanged(SwtTree.java:439)
	at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:166)
	at org.eclipse.jface.util.SafeRunnable$1.run(SafeRunnable.java:130)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:177)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:164)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2193)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1216)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1246)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:232)
	at org.eclipse.jface.util.OpenStrategy.access$3(OpenStrategy.java:226)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:403)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:869)
	at org.eclipse.jface.window.Window.open(Window.java:845)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:80)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:47)
	at org.pentaho.di.ui.repository.repositoryexplorer.RepositoryExplorer.show(RepositoryExplorer.java:146)
	at org.pentaho.di.ui.spoon.Spoon$26$1.run(Spoon.java:4146)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:193)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1201)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.ui.xul.swt.SwtBinding$1.propertyChange(SwtBinding.java:124)
	... 37 more
Caused by: java.lang.NullPointerException
	at org.pentaho.di.ui.repository.repositoryexplorer.controllers.BrowseController.setSelectedFolderItems(BrowseController.java:800)
	... 41 more
```

## Steps to Reproduce the Problem

  1. Connect a database repository
  1. Open the repository explorer
  1. Expand the folder tree on the left sidebar

### Server
  - webSpoon: 45726270

**Comment by HiromuHota** [comment]
This happens even when connected to a pentaho repository.

**Comment by HiromuHota** [comment]
Workaround: click on the folder to be expanded before clicking on the toggle icon on the left of the folder.

![workaround](https://user-images.githubusercontent.com/20668349/55036737-bcc3f580-4fd8-11e9-98a0-ef7c1aaa374b.gif)

**Comment by HiromuHota** [comment]
This issue does not happen on Spoon.

**Comment by HiromuHota** [comment]
The issue happens because the `UIRepositoryDirectory` for "New Folder" is not populated when it gets expanded.
https://github.com/pentaho/pentaho-kettle/blob/8.2.0.0-R/ui/src/main/java/org/pentaho/di/ui/repository/repositoryexplorer/controllers/BrowseController.java#L783

**Comment by HiromuHota** [comment]
Still get the following error but maybe this is something else:
```
Ignored reentrant call while viewer is busy. This is only logged once per viewer instance, but similar calls will still be ignored.
java.lang.RuntimeException
	at org.eclipse.jface.viewers.ColumnViewer.checkBusy(ColumnViewer.java:759)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setExpandedState(AbstractTreeViewer.java:2435)
	at org.pentaho.ui.xul.swt.tags.SwtTree.setTreeItemExpanded(SwtTree.java:1836)
	at org.pentaho.ui.xul.swt.tags.SwtTreeItem.setExpanded(SwtTreeItem.java:187)
	at org.pentaho.ui.xul.swt.tags.SwtTree$6.treeExpanded(SwtTree.java:375)
	at org.eclipse.jface.viewers.AbstractTreeViewer$3.run(AbstractTreeViewer.java:1105)
	at org.eclipse.jface.util.SafeRunnable$1.run(SafeRunnable.java:130)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:177)
	at org.eclipse.jface.viewers.AbstractTreeViewer.fireTreeExpanded(AbstractTreeViewer.java:1103)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleTreeExpand(AbstractTreeViewer.java:1450)
	at org.eclipse.jface.viewers.TreeViewer.handleTreeExpand(TreeViewer.java:952)
	at org.eclipse.jface.viewers.AbstractTreeViewer$4.treeExpanded(AbstractTreeViewer.java:1459)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:161)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:869)
	at org.eclipse.jface.window.Window.open(Window.java:845)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:80)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:47)
	at org.pentaho.di.ui.repository.repositoryexplorer.RepositoryExplorer.show(RepositoryExplorer.java:146)
	at org.pentaho.di.ui.spoon.Spoon$26$1.run(Spoon.java:4147)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:193)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1201)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
```

**Comment by HiromuHota** [comment]
`XulTreeContentProvider`, used by the repository explorer, implements `ITreeContentProvider` (not `ILazyContentProvider`)

> The ILazyContentProvider is the content provider for table viewers created using the SWT.VIRTUAL flag that only wish to return their contents as they are queried.

**Comment by HiromuHota** [comment]
Bug 488484 - [GTK3] "Ignored reentrant call while viewer is busy" warning and stacktrace
https://bugs.eclipse.org/bugs/show_bug.cgi?id=488484
