### ISSUE TITLE
Conversion cannot be saved

### ISSUE THREAD

**Issue by javacodeofmy** [HiromuHota/pentaho-kettle#164]
## Expected Behavior
I created a conversion task, but when I saved it, I reported an error. The error message is as follows. Do I need to make any special configuration? I deployed the latest version in a non-docker way.
![image](https://user-images.githubusercontent.com/7877585/60783677-3c3b9600-a17e-11e9-9e34-f08d4258cee1.png)
angular.js:12011 GET http://localhost:8080/spoon/osgi/cxf/browser/loadFilesAndFolders/%2F?v=1562563210.3952725&cid=7b66e406 400
(anonymous) @ angular.js:12011
q @ angular.js:11776
(anonymous) @ angular.js:11571
(anonymous) @ angular.js:16383
$eval @ angular.js:17682
$digest @ angular.js:17495
$apply @ angular.js:17790
(anonymous) @ angular.js:25890
dispatch @ jquery.js:4731
n.handle @ jquery.js:4544
angular.js:12011 GET http://localhost:8080/spoon/osgi/cxf/browser/checkForSecurityOrDupeIssues/%2F/%E8%BD%AC%E6%8D%A2%201/false?v=1562563224.837307&cid=7b66e406 400
## error message
08-Jul-2019 13:13:05.517 warn [qtp1268174061-49] org.apache.cxf.jaxrs.utils.JAXRSUtils.findTargetMethod No operation matching request path "/cxf/browser/checkForSecurityOrDupeIssues//%E8%BD%AC%E6%8D%A21/false" is found, Relative Path: /checkForSecurityOrDupeIssues//%E8%BD%AC%E6%8D%A21/false, HTTP Method: GET, ContentType: */*, Accept: application/json,. Please enable FINE/TRACE log level for more details.
08-Jul-2019 13:13:05.517 warn [qtp1268174061-49] org.apache.cxf.jaxrs.impl.WebApplicationExceptionMapper.toResponse javax.ws.rs.ClientErrorException: HTTP 404 Not Found
        at org.apache.cxf.jaxrs.utils.SpecExceptions.toHttpException(SpecExceptions.java:117)
        at org.apache.cxf.jaxrs.utils.ExceptionUtils.toHttpException(ExceptionUtils.java:173)
        at org.apache.cxf.jaxrs.utils.JAXRSUtils.findTargetMethod(JAXRSUtils.java:536)
        at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:177)
        at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:77)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:270)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:75)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)

**Comment by zhangrenhua** [comment]
你好，我也出现了这个问题，请问你是怎么解决这个问题的呀？

**Comment by zhangrenhua** [comment]
问题解决了，谢谢你，tomcat启动的时候需要执行：
export org.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
