### ISSUE TITLE
New Repository  Connection Error

### ISSUE THREAD

**Issue by zhangrenhua** [HiromuHota/pentaho-kettle#169]
Hello, when I try to create a new Repository Connection in the pentaho-kettle-webspoon-8.3 version, I get the following error message:
```
Client Error
Details
Error: Error: Operation "call" on target "w216" of type "rwt.widgets.Browser" failed:
SecurityRestriction:
Browser-Widget can not access "localhost:9051" from "localhost:8080".
Properties: 
functions = getConnectionId,closeWindow


  Script: {"head":{},"operations":[["set","w17",{"bounds":[0,0,1371,25]}],["set","w36",{"text":"撤销 : 不可获得"}],["set","w37",{"text":"重做 : 不可获得"}],["set","w42",{"text":"复制转换图片到剪贴板"}],["set","w43",{"text":"清除选择","mnemonicIndex":0}],["set","w44",{"text":"选择所有的步骤","mnemonicIndex":0}],["set","w45",{"text":"搜索元数据","mnemonicIndex":2}],["set","w46",{"text":"设置环境变量","mnemonicIndex":4}],["set","w47",{"text":"显示环境变量","mnemonicIndex":4}],["set","w48",{"text":"编辑kettle.properties文件"}],["set","w49",{"text":"显示参数(u)","mnemonicIndex":5}],["create","w215","rwt.widgets.Shell",{"style":["CLOSE","TITLE","APPLICATION_MODAL","BORDER"],"parentShell":"w2"}],["listen","w215",{"Move":true,"Resize":true,"Activate":true,"Close":true}],["set","w215",{"image":["rwt-resources/generated/605a7178.png",16,16],"text":"New Repository Connection","active":true,"minimumSize":[30,40],"activeControl":"w216","children":["w216"],"bounds":[370,130,630,630],"visibility":true}],["listen","w215",{"Traverse":true}],["create","w216","rwt.widgets.Browser",{"parent":"w215","style":["NONE"],"children":[],"bounds":[0,38,628,590],"tabIndex":1,"url":"http://localhost:9051/@pentaho/di-plugin-repositories@8.3.0.0-371/index.html#/add"}],["call","w216","createFunctions",{"functions":["getConnectionId","closeWindow"]}],["set","w1",{"focusControl":"w216"}],["set","rwt.client.ServerPush",{"active":true}],["set","w1",{"activeKeys":["CTRL+#78","ALT+CTRL+#78","CTRL+#79","CTRL+#87","CTRL+SHIFT+#87","CTRL+#83","CTRL+#73","#33","#34","#36","#120","#119","#121","SHIFT+#121","SHIFT+#122","#122","#117","#118","#119","CTRL+#69","#114","#115","CTRL+#121","CTRL+#49"],"cancelKeys":["CTRL+#78","ALT+CTRL+#78","CTRL+#79","CTRL+#87","CTRL+SHIFT+#87","CTRL+#83","CTRL+#73","#33","#34","#36","#120","#119","#121","SHIFT+#121","SHIFT+#122","#122","#117","#118","#119","CTRL+#69","#114","#115","CTRL+#121","CTRL+#49"]}]]}
  Stack: Error: Operation "call" on target "w216" of type "rwt.widgets.Browser" failed:
SecurityRestriction:
Browser-Widget can not access "localhost:9051" from "localhost:8080".
Properties: 
functions = getConnectionId,closeWindow

    at Object._processError (http://localhost:8080/spoon/rwt-resources/390/rap-client.js:226:3814)
    at Object.processOperationArray (http://localhost:8080/spoon/rwt-resources/390/rap-client.js:226:924)
    at Object.processMessage (http://localhost:8080/spoon/rwt-resources/390/rap-client.js:226:253)
    at Object._handleSuccess (http://localhost:8080/spoon/rwt-resources/390/rap-client.js:230:3439)
    at rwt.remote.Request._success (http://localhost:8080/spoon/rwt-resources/390/rap-client.js:98:925)
    at rwt.remote.Request._onReadyStateChange (http://localhost:8080/spoon/rwt-resources/390/rap-client.js:98:1596)
    at XMLHttpRequest. (http://localhost:8080/spoon/rwt-resources/390/rap-client.js:7:219)
  Debug: off
  Request: {"head":{"requestCounter":1},"operations":[["set","w2",{"mode":"maximized","bounds":[0,0,1371,890],"activeControl":"w3"}],["notify","w89","Selection",{"button":1,"shiftKey":false,"ctrlKey":false,"altKey":false}],["set","w1",{"cursorLocation":[1315,52],"focusControl":"w3"}]]}
```

**Comment by HiromuHota** [comment]
I think your installation is not complete. At least `repositories-plugin-core-8.3.0.0-371.jar` has not been replaced with the patched one.
If you do not use the Docker version, please follow the instructions at https://github.com/HiromuHota/pentaho-kettle#without-docker.

If you've completed the installation processes but the issue still persists, removing the Karaf cache like below may help.

```bash
$ ./bin/shutdown.sh
$ rm -rf ${CATALINA_HOME}/system/karaf/caches/webspoonservletcontextlistener
$ ./bin/startup.sh
```

**Comment by zhangrenhua** [comment]
thank you very much. This issue has been resolved based on the documentation you provided. thanks again.
