### ISSUE TITLE
I can't login in respository .

### ISSUE THREAD

**Issue by sywh1234-git** [HiromuHota/pentaho-kettle#172]
Dear : 
    I have another trouble than how can I login in a respository use webspoon.When the tomcat starts,my webspoon index page looks like this :
![image](https://user-images.githubusercontent.com/45229537/62413872-ea840f80-b646-11e9-8690-49f6ce811d25.png)
But I can't login in and when I input admin/admin ,it show this tip:
![rspoon](https://user-images.githubusercontent.com/45229537/62413982-b27dcc00-b648-11e9-89a3-212787764984.png)

And the catalina.out log print this error:

2019/08/03 15:25:09 - General - ERROR (version 8.3.0.0-371-19, build 8.3.0.0-371-19 from 2019-08-02 04.47.37 by worldstar) : Error calling extension points
2019/08/03 15:25:09 - General - ERROR (version 8.3.0.0-371-19, build 8.3.0.0-371-19 from 2019-08-02 04.47.37 by worldstar) : org.eclipse.rap.rwt.internal.lifecycle.UIThread$UIThreadTerminatedError
2019/08/03 15:25:09 - General - 	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.handleInterruptInSwitchThread(UIThread.java:96)
2019/08/03 15:25:09 - General - 	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.switchThread(UIThread.java:67)
2019/08/03 15:25:09 - General - 	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.sleep(RWTLifeCycle.java:232)
2019/08/03 15:25:09 - General - 	at org.eclipse.swt.widgets.Display.sleep(Display.java:1258)
2019/08/03 15:25:09 - General - 	at org.pentaho.di.ui.repo.dialog.RepositoryDialog.open(RepositoryDialog.java:97)
2019/08/03 15:25:09 - General - 	at org.pentaho.di.ui.repo.dialog.RepositoryDialog.open(RepositoryDialog.java:77)
2019/08/03 15:25:09 - General - 	at org.pentaho.di.ui.repo.dialog.RepositoryDialog.openLogin(RepositoryDialog.java:120)
2019/08/03 15:25:09 - General - 	at org.pentaho.di.ui.repo.extension.RepositorySpoonStartExtensionPoint.callExtensionPoint(RepositorySpoonStartExtensionPoint.java:98)
2019/08/03 15:25:09 - General - 	at org.pentaho.di.core.extension.ExtensionPointMap.callExtensionPoint(ExtensionPointMap.java:151)
2019/08/03 15:25:09 - General - 	at org.pentaho.di.core.extension.ExtensionPointHandler.callExtensionPoint(ExtensionPointHandler.java:45)
2019/08/03 15:25:09 - General - 	at org.pentaho.di.ui.spoon.WebSpoonEntryPoint.createContents(WebSpoonEntryPoint.java:95)
2019/08/03 15:25:09 - General - 	at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:60)
2019/08/03 15:25:09 - General - 	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
2019/08/03 15:25:09 - General - 	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
2019/08/03 15:25:09 - General - 	at java.lang.Thread.run(Thread.java:748)
2019/08/03 15:25:09 - General - 	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
2019/08/03 15:26:26 - RepositoriesMeta - Reading repositories XML file: C:\Users\worldstar\.kettle\repositories.xml
Graphics2D from BufferedImage lacks BUFFERED_IMAGE hint

And my chrome brower's console show this error : 
![image](https://user-images.githubusercontent.com/45229537/62413890-4189e480-b647-11e9-90f3-c6b97216a428.png)

the port 3600 is my tomcat http port,what is 9051 port for ?

**Comment by sywh1234-git** [comment]
Finally, after I've replaced the relevant jars, I finally see the interface:
![image](https://user-images.githubusercontent.com/45229537/62455744-a2c9c900-b7a9-11e9-944a-9dc898d8a6d2.png)

![image](https://user-images.githubusercontent.com/45229537/62455795-bc6b1080-b7a9-11e9-91be-72d4561ee273.png)
