### ISSUE TITLE
I tried to install the splunk plugin in the marketplace

### ISSUE THREAD

**Issue by kundeng** [HiromuHota/pentaho-kettle#173]
## Expected Behavior
should install

## Actual Behavior
Screenshots and error messages are helpful.
invalid plugin ids. 
### Server
  - OS (e.g., Mac OS X 10.12.6):
  - Java (e.g., Oracle JDK 8u151):
  - Servlet container (e.g., Apache Tomcat 8.5.20):
  - webSpoon (e.g., version: 0.8.0.13 or commitId: 0211d84b):

### Client
  - OS (e.g., Mac OS X 10.12.6):
  - Browser (e.g., Google Chrome 64.0.3282.140):

**Comment by HiromuHota** [comment]
Does this issue happen on Spoon too?

**Comment by HiromuHota** [comment]
I confirmed that this issue happened on Spoon too.
I'm afraid but I won't fix this. Please report this issue to Pentaho Jira (https://jira.pentaho.com).

**Comment by HiromuHota** [comment]
Though I won't fix this, I found a workaround.

1. Download https://github.com/saschagrebe/kettle-splunk-plugin/releases/download/v1.0.0/splunk-plugin-1.0.0-bin.zip
2. Extract the zip file at `$CATALINA_HOME/plugins/`
3. Restart webSpoon

**Comment by HiromuHota** [comment]
Reported at https://jira.pentaho.com/browse/PDI-18267.

**Comment by kundeng** [comment]
FYI,  even after it is installed,  it still doesn't work with the latest version of splunk.  If I have to guess it has something to do SSL. 

java.lang.RuntimeException: Connection refused (Connection refused)
	at com.splunk.HttpService.send(HttpService.java:409)
	at com.splunk.Service.send(Service.java:1293)
	at com.splunk.HttpService.post(HttpService.java:308)
	at com.splunk.Service.login(Service.java:1122)
	at com.splunk.Service.login(Service.java:1101)
	at com.splunk.Service.connect(Service.java:187)
	at de.sagr.kettle.splunkplugin.adapter.SplunkAdapter.init(SplunkAdapter.java:28)
	at de.sagr.kettle.splunkplugin.input.InputStepDialog.loadFieldsForQuery(InputStepDialog.java:498)
	at de.sagr.kettle.splunkplugin.input.InputStepDialog.access$300(InputStepDialog.java:42)
	at de.sagr.kettle.splunkplugin.input.InputStepDialog$4.handleEvent(InputStepDialog.java:327)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at de.sagr.kettle.splunkplugin.input.InputStepDialog.openDialog(InputStepDialog.java:369)
	at de.sagr.kettle.splunkplugin.input.InputStepDialog.open(InputStepDialog.java:105)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:120)
	at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:8901)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3431)
	at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:819)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:218)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at com.splunk.HttpService.send(HttpService.java:403)
	... 35 more

**Comment by HiromuHota** [comment]
If you use a self-signed certificate for SSL, please look at the following article.
https://help.pentaho.com/Documentation/8.0/Setup/Administration/User_Security/Securing_Pentaho_Server_and_Pentaho_User_Console_(PUC)_with_SSL/000/010/000
