### ISSUE TITLE
Get Fields of Fixed Input causes an NPE error

### ISSUE THREAD

**Issue by HiromuHota** [HiromuHota/pentaho-kettle#18]
Clicking on Get Fields of Fixed Input gives the following error.
The other editing and execution work fine.
```
java.lang.NullPointerException
	at org.eclipse.swt.graphics.GC.textExtent(GC.java:254)
	at org.pentaho.di.ui.trans.steps.fixedinput.FixedTableDraw.<init>(FixedTableDraw.java:124)
	at org.pentaho.di.ui.trans.steps.fixedinput.FixedFileImportWizardPage1.createControl(FixedFileImportWizardPage1.java:80)
	at org.pentaho.di.ui.trans.steps.fixedinput.FixedInputDialog.getFixed(FixedInputDialog.java:783)
	at org.pentaho.di.ui.trans.steps.fixedinput.FixedInputDialog.access$5(FixedInputDialog.java:727)
	at org.pentaho.di.ui.trans.steps.fixedinput.FixedInputDialog$7.handleEvent(FixedInputDialog.java:483)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.pentaho.di.ui.trans.steps.fixedinput.FixedInputDialog.open(FixedInputDialog.java:544)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:125)
	at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:8776)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3123)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:2188)
	at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDown(TransGraph.java:867)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:214)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
```

**Comment by HiromuHota** [comment]
Resolved by d63edf10d9aa0b4b9183a07e32bbdee83b894f57.
