### ISSUE TITLE
org.apache.felix.resolver.reason.ReasonException

### ISSUE THREAD

**Issue by lucienhsu** [HiromuHota/pentaho-kettle#198]
## Actual Behavior
```
2020-03-31 16:17:47.675:INFO:oejsh.ContextHandler:features-3-thread-1: Started HttpServiceContext{httpContext=DefaultHttpContext [bundle=pentaho-pdi-platform [250], contextID=default]}
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=repositories-plugin; type=karaf.feature; version="[9.0.0.0-423,9.0.0.0-423]"; filter:="(&(osgi.identity=repositories-plugin)(type=karaf.feature)(version>=9.0.0.0-423)(version<=9.0.0.0-423))" [caused by: Unable to resolve repositories-plugin/9.0.0.0-423: missing requirement [repositories-plugin/9.0.0.0-423] osgi.identity; osgi.identity=repositories-plugin-core; type=osgi.bundle; version="[9.0.0.0-423,9.0.0.0-423]"; resolution:=mandatory [caused by: Unable to resolve repositories-plugin-core/9.0.0.0-423: missing requirement [repositories-plugin-core/9.0.0.0-423] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.eclipse.rap.rwt)(version>=3.12.0)(!(version>=4.0.0)))"]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:392)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:378)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:332)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve repositories-plugin/9.0.0.0-423: missing requirement [repositories-plugin/9.0.0.0-423] osgi.identity; osgi.identity=repositories-plugin-core; type=osgi.bundle; version="[9.0.0.0-423,9.0.0.0-423]"; resolution:=mandatory [caused by: Unable to resolve repositories-plugin-core/9.0.0.0-423: missing requirement [repositories-plugin-core/9.0.0.0-423] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.eclipse.rap.rwt)(version>=3.12.0)(!(version>=4.0.0)))"]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve repositories-plugin-core/9.0.0.0-423: missing requirement [repositories-plugin-core/9.0.0.0-423] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.eclipse.rap.rwt)(version>=3.12.0)(!(version>=4.0.0)))"
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 13 more
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=file-open-save-plugin; type=karaf.feature; version="[9.0.0.0-423,9.0.0.0-423]"; filter:="(&(osgi.identity=file-open-save-plugin)(type=karaf.feature)(version>=9.0.0.0-423)(version<=9.0.0.0-423))" [caused by: Unable to resolve file-open-save-plugin/9.0.0.0-423: missing requirement [file-open-save-plugin/9.0.0.0-423] osgi.identity; osgi.identity=file-open-save-core; type=osgi.bundle; version="[9.0.0.0-423,9.0.0.0-423]"; resolution:=mandatory [caused by: Unable to resolve file-open-save-core/9.0.0.0-423: missing requirement [file-open-save-core/9.0.0.0-423] osgi.wiring.package; filter:="(osgi.wiring.package=org.pentaho.di.ui.repo.endpoints)"]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:392)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:378)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:332)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve file-open-save-plugin/9.0.0.0-423: missing requirement [file-open-save-plugin/9.0.0.0-423] osgi.identity; osgi.identity=file-open-save-core; type=osgi.bundle; version="[9.0.0.0-423,9.0.0.0-423]"; resolution:=mandatory [caused by: Unable to resolve file-open-save-core/9.0.0.0-423: missing requirement [file-open-save-core/9.0.0.0-423] osgi.wiring.package; filter:="(osgi.wiring.package=org.pentaho.di.ui.repo.endpoints)"]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve file-open-save-core/9.0.0.0-423: missing requirement [file-open-save-core/9.0.0.0-423] osgi.wiring.package; filter:="(osgi.wiring.package=org.pentaho.di.ui.repo.endpoints)"
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 13 more
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=file-open-save-new-plugin; type=karaf.feature; version="[9.0.0.0-423,9.0.0.0-423]"; filter:="(&(osgi.identity=file-open-save-new-plugin)(type=karaf.feature)(version>=9.0.0.0-423)(version<=9.0.0.0-423))" [caused by: Unable to resolve file-open-save-new-plugin/9.0.0.0-423: missing requirement [file-open-save-new-plugin/9.0.0.0-423] osgi.identity; osgi.identity=file-open-save-new-core; type=osgi.bundle; version="[9.0.0.0-423,9.0.0.0-423]"; resolution:=mandatory [caused by: Unable to resolve file-open-save-new-core/9.0.0.0-423: missing requirement [file-open-save-new-core/9.0.0.0-423] osgi.wiring.package; filter:="(osgi.wiring.package=org.pentaho.di.ui.repo.endpoints)"]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:392)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:378)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:332)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve file-open-save-new-plugin/9.0.0.0-423: missing requirement [file-open-save-new-plugin/9.0.0.0-423] osgi.identity; osgi.identity=file-open-save-new-core; type=osgi.bundle; version="[9.0.0.0-423,9.0.0.0-423]"; resolution:=mandatory [caused by: Unable to resolve file-open-save-new-core/9.0.0.0-423: missing requirement [file-open-save-new-core/9.0.0.0-423] osgi.wiring.package; filter:="(osgi.wiring.package=org.pentaho.di.ui.repo.endpoints)"]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve file-open-save-new-core/9.0.0.0-423: missing requirement [file-open-save-new-core/9.0.0.0-423] osgi.wiring.package; filter:="(osgi.wiring.package=org.pentaho.di.ui.repo.endpoints)"
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 13 more

```
## Steps to Reproduce the Problem
  1. mvn clean install 

## Specifications
As above, how to solve the above error reporting.
Thanks.

**Comment by HiromuHota** [comment]
Assuming that you've built webSpoon yourself, please 
1. Follow steps described [here](https://github.com/HiromuHota/pentaho-kettle#without-docker) and confirm it works.
2. Start customizing the install.sh script so that the script installs your built war file.

Hope this helps.

**Comment by HiromuHota** [comment]
Close due to no response from the reporter. Feel free to reopen it if the issue still persists.
