### ISSUE TITLE
Duplicate folders in Repository Explorer

### ISSUE THREAD

**Issue by gustavoaalves** [HiromuHota/pentaho-kettle#199]
## Expected Behavior
When i click on Tools > Repository > Explore.. , a windows must be opened with the home and public folders.

## Actual Behavior
When i click on Tools > Repository > Explore.. , a windows is open but with the home folders are duplicated.

![image](https://user-images.githubusercontent.com/11478696/79249742-1604fe00-7e54-11ea-856d-c54f3ff5b8e3.png)

## Steps to Reproduce the Problem

  1. Click on Tools > Repository > Explore when user is connected to a Pentaho Repository.

### Server
  - OS: Windows 10 Pro with Docker
  - Java (e.g., Oracle JDK 8u151): Docker container
  - Servlet container (e.g., Apache Tomcat 8.5.20):
  - webSpoon (e.g., version: 0.8.0.13 or commitId: 0211d84b): Docker container hiromuhota/webspoon

### Client
  - OS (e.g., Mac OS X 10.12.6): Windows 10 Home
  - Browser (e.g., Google Chrome 64.0.3282.140): Google Chrome 81.0.4044.92 (Versão oficial) 64 bits

**Comment by HiromuHota** [comment]
Thank you for reporting.
For a record, this issue does not happen on Spoon (PDI CE 9.0), but happens on webSpoon (0.9.0.21).

I've noticed that the following error message appeared:
```
Ignored reentrant call while viewer is busy. This is only logged once per viewer instance, but similar calls will still be ignored.
java.lang.RuntimeException
	at org.eclipse.jface.viewers.ColumnViewer.checkBusy(ColumnViewer.java:759)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setExpandedState(AbstractTreeViewer.java:2435)
	at org.pentaho.ui.xul.swt.tags.SwtTree.setTreeItemExpanded(SwtTree.java:1836)
	at org.pentaho.ui.xul.swt.tags.SwtTreeItem.setExpanded(SwtTreeItem.java:187)
	at org.pentaho.ui.xul.swt.tags.SwtTree$6.treeExpanded(SwtTree.java:375)
	at org.eclipse.jface.viewers.AbstractTreeViewer$3.run(AbstractTreeViewer.java:1105)
	at org.eclipse.jface.util.SafeRunnable$1.run(SafeRunnable.java:130)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:177)
	at org.eclipse.jface.viewers.AbstractTreeViewer.fireTreeExpanded(AbstractTreeViewer.java:1103)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleTreeExpand(AbstractTreeViewer.java:1450)
	at org.eclipse.jface.viewers.TreeViewer.handleTreeExpand(TreeViewer.java:952)
	at org.eclipse.jface.viewers.AbstractTreeViewer$4.treeExpanded(AbstractTreeViewer.java:1459)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:161)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:869)
	at org.eclipse.jface.window.Window.open(Window.java:845)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:89)
	at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:56)
	at org.pentaho.di.ui.repository.repositoryexplorer.RepositoryExplorer.show(RepositoryExplorer.java:146)
	at org.pentaho.di.ui.spoon.Spoon$26$1.run(Spoon.java:4172)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:193)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1201)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
```

**Comment by gustavoaalves** [comment]
Glad for your fast action in this issue. 
Where did you get this erro message? Which log file?

**Comment by HiromuHota** [comment]
You can see this log by `docker logs -f webspoon` or directly look at `/usr/local/tomcat/logs/catalina.2020-XX-XX.log`.

**Comment by HiromuHota** [comment]
I confirmed that this issue was reproducible on 8.2 and 8.3. Not confirmed, but maybe older versions too.

**Comment by HiromuHota** [comment]
A related issue has been reported at https://github.com/HiromuHota/pentaho-kettle/issues/146#issuecomment-477268168.

**Comment by HiromuHota** [comment]
Maybe related: https://bugs.eclipse.org/bugs/show_bug.cgi?id=207336
