### ISSUE TITLE
Unable to start container for blueprint bundle file-open-save-core/9.0.0.0-423

### ISSUE THREAD

**Issue by fantasyWJP** [HiromuHota/pentaho-kettle#224]
when i start the webSpoon9.0,there's sth wrong in spoon.log:
2021-01-11 14:27:48,247 WARN  [org.apache.aries.blueprint.container.BeanRecipe] Object to be destroyed is not an instance of UnwrapperedBeanHolder, type: null
2021-01-11 14:27:48,252 ERROR [org.apache.aries.blueprint.container.BlueprintContainerImpl] Unable to start container for blueprint bundle file-open-save-core/9.0.0.0-423
org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to instantiate components
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:741)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:433)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:298)
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:311)
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:280)
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:276)
	at org.apache.aries.blueprint.container.BlueprintExtender.modifiedBundle(BlueprintExtender.java:266)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:500)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:433)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$AbstractTracked.track(BundleHookBundleTracker.java:725)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.bundleChanged(BundleHookBundleTracker.java:463)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$BundleEventHook.event(BundleHookBundleTracker.java:422)
	at org.apache.felix.framework.util.SecureAction.invokeBundleEventHook(SecureAction.java:1179)
	at org.apache.felix.framework.EventDispatcher.createWhitelistFromHooks(EventDispatcher.java:730)
	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:485)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2174)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1153)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1036)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: javax/ws/rs/container/ContainerRequestFilter
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2408)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:855)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1327)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.felix.framework.ExtensionManager$ExtensionManagerWiring.getClassByDelegation(ExtensionManager.java:940)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1660)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1590)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.felix.framework.Felix.loadBundleClass(Felix.java:1927)
	at org.apache.felix.framework.BundleImpl.loadClass(BundleImpl.java:978)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.loadClass(BlueprintContainerImpl.java:471)
	at org.apache.aries.blueprint.container.BlueprintRepository.loadClass(BlueprintRepository.java:524)
	at org.apache.aries.blueprint.container.GenericType.parse(GenericType.java:135)
	at org.apache.aries.blueprint.di.AbstractRecipe.doLoadType(AbstractRecipe.java:169)
	at org.apache.aries.blueprint.di.AbstractRecipe.loadType(AbstractRecipe.java:162)
	at org.apache.aries.blueprint.container.BeanRecipe.loadClass(BeanRecipe.java:251)
	at org.apache.aries.blueprint.container.BeanRecipe.getType(BeanRecipe.java:772)
	at org.apache.aries.blueprint.container.BeanRecipe.getInstanceFromType(BeanRecipe.java:342)
	at org.apache.aries.blueprint.container.BeanRecipe.getInstance(BeanRecipe.java:283)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:685)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:666)
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:108)
	at org.apache.aries.blueprint.di.CollectionRecipe.internalCreate(CollectionRecipe.java:90)
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:108)
	at org.apache.aries.blueprint.container.BeanRecipe.setProperty(BeanRecipe.java:810)
	at org.apache.aries.blueprint.container.BeanRecipe.setProperties(BeanRecipe.java:784)
	at org.apache.aries.blueprint.container.BeanRecipe.setProperties(BeanRecipe.java:765)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:699)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:666)
	at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:81)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:90)
	at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:360)
	at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:190)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:737)
	... 28 more
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.container.ContainerRequestFilter
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1358)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1180)
	... 70 more

also repositories-plugin-core has the same error:
2021-01-11 14:27:43,452 WARN  [org.apache.aries.blueprint.container.BeanRecipe] Object to be destroyed is not an instance of UnwrapperedBeanHolder, type: null
2021-01-11 14:27:43,457 ERROR [org.apache.aries.blueprint.container.BlueprintContainerImpl] Unable to start container for blueprint bundle repositories-plugin-core/9.0.0.0-423
org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to instantiate components
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:741)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:433)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:298)
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:311)
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:280)
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:276)
	at org.apache.aries.blueprint.container.BlueprintExtender.modifiedBundle(BlueprintExtender.java:266)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:500)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:433)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$AbstractTracked.track(BundleHookBundleTracker.java:725)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.bundleChanged(BundleHookBundleTracker.java:463)
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$BundleEventHook.event(BundleHookBundleTracker.java:422)
	at org.apache.felix.framework.util.SecureAction.invokeBundleEventHook(SecureAction.java:1179)
	at org.apache.felix.framework.EventDispatcher.createWhitelistFromHooks(EventDispatcher.java:730)
	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:485)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2174)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1153)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1036)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/osgi/service/http/HttpContext
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2408)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:855)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1327)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.felix.framework.ExtensionManager$ExtensionManagerWiring.getClassByDelegation(ExtensionManager.java:940)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1660)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1590)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.felix.framework.Felix.loadBundleClass(Felix.java:1927)
	at org.apache.felix.framework.BundleImpl.loadClass(BundleImpl.java:978)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.loadClass(BlueprintContainerImpl.java:471)
	at org.apache.aries.blueprint.container.BlueprintRepository.loadClass(BlueprintRepository.java:524)
	at org.apache.aries.blueprint.container.GenericType.parse(GenericType.java:135)
	at org.apache.aries.blueprint.di.AbstractRecipe.doLoadType(AbstractRecipe.java:169)
	at org.apache.aries.blueprint.di.AbstractRecipe.loadType(AbstractRecipe.java:162)
	at org.apache.aries.blueprint.container.BeanRecipe.loadClass(BeanRecipe.java:251)
	at org.apache.aries.blueprint.container.BeanRecipe.getType(BeanRecipe.java:772)
	at org.apache.aries.blueprint.container.BeanRecipe.getInstanceFromType(BeanRecipe.java:342)
	at org.apache.aries.blueprint.container.BeanRecipe.getInstance(BeanRecipe.java:283)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:685)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:666)
	at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:81)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:90)
	at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:360)
	at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:190)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:737)
	... 28 more
Caused by: java.lang.ClassNotFoundException: org.osgi.service.http.HttpContext
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1358)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1180)
	... 62 more

the bundle has the pom dependency and MANIFEST.MF has include the right Import-package。
i dont't konw what todo after try many times.

**Comment by fantasyWJP** [comment]
i was develop on IDEA，that i push all module compile output and jars to spoon.war, thar's not correct。
i comparison the download spoon.war libs directory to my compile spoon.war, i remove some jar,then spoon.log is correct.
but i've got NPE when i choose a transformation on job:
Graphics2D from BufferedImage lacks BUFFERED_IMAGE hint
12-Jan-2021 14:13:30.458 璀﹀憡 [qtp1488283356-122] org.apache.cxf.phase.PhaseInterceptorChain.doDefaultLogging Application {http://endpoints.fileopensave.plugins.di.pentaho.org/}FileBrowserEndpoint has thrown exception, unwinding now
	org.apache.cxf.interceptor.Fault
		at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:162)
		at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:128)
		at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
		at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
		at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
		at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
		at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
		at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
		at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
		at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
		at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
		at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
		at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
		at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
		at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
		at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
		at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
		at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
		at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
		at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
		at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
		at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
		at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
		at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:293)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
		at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
		at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
		at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
		at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
		at org.eclipse.jetty.server.handler.IPAccessHandler.handle(IPAccessHandler.java:221)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
		at org.eclipse.jetty.server.Server.handle(Server.java:505)
		at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
		at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
		at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
		at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
		at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
		at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.NullPointerException
		at org.pentaho.di.plugins.fileopensave.providers.repository.RepositoryFileProvider.getTree(RepositoryFileProvider.java:99)
		at org.pentaho.di.plugins.fileopensave.providers.repository.RepositoryFileProvider.getTree(RepositoryFileProvider.java:70)
		at org.pentaho.di.plugins.fileopensave.api.providers.FileProvider.getTree(FileProvider.java:59)
		at Proxy1c4ffded_f05f_42f2_8a18_e432ea3d035e.getTree(Unknown Source)
		at org.pentaho.di.plugins.fileopensave.controllers.FileController.load(FileController.java:94)
		at org.pentaho.di.plugins.fileopensave.endpoints.FileBrowserEndpoint.loadDirectoryTree(FileBrowserEndpoint.java:70)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
		at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)

**Comment by fantasyWJP** [comment]
i figure it out: some guy just set one transformation name to null in database,in org.pentaho.di.plugins.fileopensave.providers.repository.RepositoryFileProvider#populateFiles  cause Exception, delete the empty name transformation, every thing is all right,the world is peace.
