### ISSUE TITLE
Run in server (Carte) causes NPE error

### ISSUE THREAD

**Issue by HiromuHota** [HiromuHota/pentaho-kettle#24]
A transformation can be submitted and executed, but a NPE error occurs when opening a monitor tab.
```
Caused by:

org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:3720)
	at org.eclipse.swt.SWT.error(SWT.java:3643)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:200)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1201)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
Caused by: java.lang.NullPointerException
	at org.eclipse.swt.graphics.GC.textExtent(GC.java:254)
	at org.pentaho.di.ui.core.widget.TreeUtil.setOptimalWidthOnColumns(TreeUtil.java:41)
	at org.pentaho.di.ui.spoon.SpoonSlave.refreshView(SpoonSlave.java:935)
	at org.pentaho.di.ui.spoon.SpoonSlave.refreshViewAndLog(SpoonSlave.java:595)
	at org.pentaho.di.ui.spoon.SpoonSlave$12$1.run(SpoonSlave.java:1221)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:193)
	... 8 more
Caused by:

java.lang.NullPointerException
	at org.eclipse.swt.graphics.GC.textExtent(GC.java:254)
	at org.pentaho.di.ui.core.widget.TreeUtil.setOptimalWidthOnColumns(TreeUtil.java:41)
	at org.pentaho.di.ui.spoon.SpoonSlave.refreshView(SpoonSlave.java:935)
	at org.pentaho.di.ui.spoon.SpoonSlave.refreshViewAndLog(SpoonSlave.java:595)
	at org.pentaho.di.ui.spoon.SpoonSlave$12$1.run(SpoonSlave.java:1221)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:193)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1201)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
```

**Comment by HiromuHota** [comment]
Resolved by 69818e5996efeec102a434b5ffe0bb15981b6c61.
