### ISSUE TITLE
webspoon start error:org.pentaho.di.osgi.OSGIPluginTrackerException: Service Reference is null. This is fatal

### ISSUE THREAD

**Issue by mingxixiao** [HiromuHota/pentaho-kettle#241]
Why to appear the following OSGIPluginTrackerException exception：

2021-07-13 08:54:37,655 ERROR [org.pentaho.di.osgi.service.notifier.DelayedInstanceNotifier] Error getting bean factory
org.pentaho.di.osgi.OSGIPluginTrackerException: Service Reference is null. This is fatal.
	at org.pentaho.di.osgi.OSGIPluginTracker.findOrCreateBeanFactoryFor(OSGIPluginTracker.java:274)
	at org.pentaho.di.osgi.service.notifier.DelayedInstanceNotifier.run(DelayedInstanceNotifier.java:64)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mingxixiao** [comment]
sloved.
