### ISSUE TITLE
Click Connect in webspoon to report an error

### ISSUE THREAD

**Issue by GSHF** [HiromuHota/pentaho-kettle#242]
Click Connect in webspoon to report an error
The error is shown in the figure below

![image](https://user-images.githubusercontent.com/38513540/126579605-9b329cd4-d0e2-4ccd-93a7-19d9afeae10b.png)

Details of the error report are as follows:
Error: Error: Operation "call" on target "w202" of type "rwt.widgets.Browser" failed:
SecurityRestriction:
Browser-Widget can not access "127.0.0.1:9051" from "apachekudu:8080".
Properties: 
functions = getConnectionId,closeWindow

  Script: {"head":{},"operations":[["set","w17",{"bounds":[0,0,1366,25]}],["set","w37",{"text":"Undo : not available"}],["set","w38",{"text":"Redo : not available"}],["set","w43",{"text":"Snapshot Canvas"}],["set","w44",{"text":"Clear","mnemonicIndex":0}],["set","w45",{"text":"Select all","mnemonicIndex":0}],["set","w46",{"text":"Search Meta data...","mnemonicIndex":7}],["set","w47",{"text":"Set Environment Variables...","mnemonicIndex":16}],["set","w48",{"text":"Show Used Environment Variables...","mnemonicIndex":22}],["set","w49",{"text":"Edit the kettle.properties file..."}],["set","w50",{"text":"Show Arguments...","mnemonicIndex":8}],["create","w201","rwt.widgets.Shell",{"style":["CLOSE","TITLE","APPLICATION_MODAL","BORDER"],"parentShell":"w2"}],["listen","w201",{"Move":true,"Resize":true,"Activate":true,"Close":true}],["set","w201",{"image":["rwt-resources/generated/605a7178.png",16,16],"text":"New Repository Connection","active":true,"minimumSize":[30,40],"activeControl":"w202","children":["w202"],"bounds":[368,-2,630,630],"visibility":true}],["listen","w201",{"Traverse":true}],["create","w202","rwt.widgets.Browser",{"parent":"w201","style":["NONE"],"children":[],"bounds":[0,38,628,590],"tabIndex":1,"url":"http://127.0.0.1:9051/@pentaho/di-plugin-repositories@9.0.0.0-SNAPSHOT/index.html#/add"}],["call","w202","createFunctions",{"functions":["getConnectionId","closeWindow"]}],["set","w1",{"focusControl":"w202"}],["set","rwt.client.ServerPush",{"active":true}],["set","w1",{"activeKeys":["CTRL+#78","ALT+CTRL+#78","CTRL+#79","CTRL+#87","CTRL+SHIFT+#87","CTRL+#83","CTRL+#73","#33","#34","#36","#120","#119","#121","SHIFT+#121","SHIFT+#122","#122","#117","#118","#119","CTRL+#69","#114","#115","CTRL+#121"],"cancelKeys":["CTRL+#78","ALT+CTRL+#78","CTRL+#79","CTRL+#87","CTRL+SHIFT+#87","CTRL+#83","CTRL+#73","#33","#34","#36","#120","#119","#121","SHIFT+#121","SHIFT+#122","#122","#117","#118","#119","CTRL+#69","#114","#115","CTRL+#121"]}]]}
  Stack: Error: Operation "call" on target "w202" of type "rwt.widgets.Browser" failed:
SecurityRestriction:
Browser-Widget can not access "127.0.0.1:9051" from "apachekudu:8080".
Properties: 
functions = getConnectionId,closeWindow

    at Object._processError (http://apachekudu:8080/spoon/rwt-resources/3120/rap-client.js:226:3814)
    at Object.processOperationArray (http://apachekudu:8080/spoon/rwt-resources/3120/rap-client.js:226:924)
    at Object.processMessage (http://apachekudu:8080/spoon/rwt-resources/3120/rap-client.js:226:253)
    at Object._handleSuccess (http://apachekudu:8080/spoon/rwt-resources/3120/rap-client.js:230:3677)
    at rwt.remote.Request._success (http://apachekudu:8080/spoon/rwt-resources/3120/rap-client.js:98:925)
    at rwt.remote.Request._onReadyStateChange (http://apachekudu:8080/spoon/rwt-resources/3120/rap-client.js:98:1596)
    at XMLHttpRequest. (http://apachekudu:8080/spoon/rwt-resources/3120/rap-client.js:7:219)
  Debug: off
  Request: {"head":{"requestCounter":1},"operations":[["set","w2",{"mode":"maximized","bounds":[0,0,1366,625],"activeControl":"w3"}],["notify","w89","Selection",{"button":1,"shiftKey":false,"ctrlKey":false,"altKey":false}],["set","w1",{"cursorLocation":[1283,43],"focusControl":"w3"}]]}

**Comment by nitar** [comment]
I have encountered the same error,please give some advice,thanks

**Comment by Linkliqi** [comment]
Has the problem been solved？I also encountered the same error

**Comment by miki-hmt** [comment]
我已经找出问题原因了，亲测通过，想知道方法的加我QQ-1329289117

**Comment by zhujiebing** [comment]
I encountered the same problem, how can I solve it？QQ408989025   @miki-hmt @Linkliqi @nitar @GSHF @HiromuHota
