### ISSUE TITLE
BaseStepDialog_ConnectionLine_Test fails

### ISSUE THREAD

**Issue by HiromuHota** [HiromuHota/pentaho-kettle#31]
This is a regression caused by fa80df7d41f865c88010049785974474edff6f5b.

```
Class	Name	Status	Type	Time(s)
BaseStepDialog_ConnectionLine_Test	showDbDialog_ReturnsNull_OnCancel	Error	Argument cannot be null

java.lang.IllegalArgumentException: Argument cannot be null
at org.eclipse.swt.SWT.error(SWT.javva:3706)
at org.eclipse.swt.SWT.error(SWT.java:3643)
at org.eclipse.swt.SWT.error(SWT.java:3614)
at org.eclipse.swt.widgets.Dialog.checkParent(Dialog.java:2992)
at org.eclipse.swt.widgets.Dialog.<init>(Dialog.java:115)
at org.pentaho.di.ui.core.dialog.ErrorDialog.<init>(ErrorDialog.java:97)
at org.pentaho.di.ui.core.database.dialog.XulDatabaseDialog.createDialog(XulDatabaseDialog.java:159)
at org.pentaho.di.ui.core.database.dialog.XulDatabaseDialog.open(XulDatabaseDialog.java:105)
at org.pentaho.di.ui.core.database.dialog.DatabaseDialog.open(DatabaseDialog.java:60)
at org.pentaho.di.ui.trans.step.BaseStepDialog.showDbDialogUnlessCancelledOrValid(BaseStepDialog.java:776)
at org.pentaho.di.ui.trans.step.BaseStepDialog_ConnectionLine_Test.test_showDbDialogUnlessCancelledOrValid_ShownOnce(BaseStepDialog_ConnectionLine_Test.java:206)
at org.pentaho.di.ui.trans.step.BaseStepDialog_ConnectionLine_Test.showDbDialog_ReturnsNull_OnCancel(BaseStepDialog_ConnectionLine_Test.java:171)
	0.194
BaseStepDialog_ConnectionLine_Test	showDbDialog_ReturnsInputName_WhenItIsUnique	Error	Argument cannot be null

java.lang.IllegalArgumentException: Argument cannot be null
at org.eclipse.swt.SWT.error(SWT.java:3706)
at org.eclipse.swt.SWT.error(SWT.java:3643)

at org.eeclipse.swt.SWT.error(SWT.java:3614)
at org.eclipse.swt.widgets.Dialog.checkParent(Dialog.java:292)
at org.eclipse.swt.widgets.Dialog..<init>(Dialog.java:115)
at org.pentaho.di.ui.core.dialog.ErrorDialog.<init>(ErrorDialog.java:97)
at org.pentaho.di.ui.core.database.dialog.XulDatabaseDialog..createDialog(XulDatabaseDialog.java:159)
at org.pentaho.di.ui.core.database.dialog.XulDatabaseDiallog.open(XulDatabaseDialog.java:105)
at org.pentaho.di.ui.core.database.dialog.DatabaseDialog.open(DatabaseDialog.java:60)
at org.pentaho.di.ui.trans.step.BaseStepDialog.showDbDialogUnlessCancelledOrValid(BaseStepDDialog.java:776)
at org.pentaho.di.ui.trans.step.BaseStepDialog_ConnectionLine__Test.test_showDbDialogUnlessCancelledOrValid_ShownOnce(BaseStepDialog_ConnectionLine_Test.java:206)
at org.pentaho.di.ui.trans.step.BaseStepDialog_ConnectionLine_Test.showDbDialoog_ReturnsInputName_WhenItIsUnique(BaseStepDialog_ConnectionLine_Test.java:176)
	0.010
BaseStepDialog_ConnectionLine_Test	showDbDialog_ReturnsInputName_WhenItIsUnique_WithSpaces	Error	Argument cannot be null

java.lang.IllegalArgumentException: Argument cannot be null
at org.eclipse.swt.SWT.error(SWT.javva:3706)
at org.eclipse.swt.SWT.error(SWT.java:3643)
at org.eclipse.swt.SWT.error(SWT.java:3614)
at org.eclipse.swt.widgets.Dialog.checkParent(Dialog.java:2992)
at org.eclipse.swt.widgets.Dialog.<init>(Dialog.java:115)
at org.pentaho.di.ui.core.dialog.ErrorDialog.<init>(ErrorDialog.java:97)
at org.pentaho.di.ui.core.database.dialog.XulDatabaseDialog.createDialog(XulDatabaseDialog.java:159)
at org.pentaho.di.ui.core.database.dialog.XulDatabaseDialog.open(XulDatabaseDialog.java:105)
at org.pentaho.di.ui.core.database.dialog.DatabaseDialog.open(DatabaseDialog.java:60)
at org.pentaho.di.ui.trans.step.BaseStepDialog.showDbDialogUnlessCancelledOrValid(BaseStepDialog.java:776)
at org.pentaho.di.ui.trans.step.BaseStepDialog_ConnectionLine_Test.test_showDbDialogUnlessCancelledOrValid_ShownOnce(BaseStepDialog_ConnectionLine_Test.java:206)
at org.pentaho.di.ui.trans.step.BaseStepDialog_ConnectionLine_Test.showDbDialog_ReturnsInputName_WhenItIsUnique_WithSpaces(BaseStepDialog_ConnectionLine_Test.java:182)
	0.009
BaseStepDialog_ConnectionLine_Test	showDbDialog_ReturnsExistingName_WhenNameWasNotChanged	Error	Argument cannot be null

java.lang.IllegalArgumentException: Argument cannot be null
at org.eclipse.swt.SWT.error(SWT.java:3706)
at org.eclipse.swt.SWT.error(SWT.java:3643)

at org.eeclipse.swt.SWT.error(SWT.java:3614)
at org.eclipse.swt.widgets.Dialog.checkParent(Dialog.java:292)
at org.eclipse.swt.widgets.Dialog..<init>(Dialog.java:115)
at org.pentaho.di.ui.core.dialog.ErrorDialog.<init>(ErrorDialog.java:97)
at org.pentaho.di.ui.core.database.dialog.XulDatabaseDialog..createDialog(XulDatabaseDialog.java:159)
at org.pentaho.di.ui.core.database.dialog.XulDatabaseDialog.oppen(XulDatabaseDialog.java:105)
at org.pentaho.di.ui.core.database.dialog.DatabaseDialog.open(DatabaseDialog.java:60)
at org.pentaho.di.ui.trans.step.BaseStepDialog.showDbDialogUnlessCancelledOrValid(BaseStepDDialog.java:776)
at org.pentaho.di.ui.trans.step.BaseStepDialog_ConnectionLine_Test..test_showDbDialogUnlessCancelledOrValid_ShownOnce(BaseStepDialog_ConnectionLine_Test.java:206)
at org.pentaho.di.ui.trans.step.BaseStepDialog_ConnectionLine_Test.showDbDialog_RetturnsExistingName_WhenNameWasNotChanged(BaseStepDialog_ConnectionLine_Test.java:188)
	0.021
BaseStepDialog_ConnectionLine_Test	showDbDialog_LoopsUntilUniqueValueIsInput	Error	Argument cannot be null

java.lang.IllegalArgumentException: Argument cannot be null
at org.eclipse.swt.SWT.error(SWT.java:3706)
at org.eclipse.swt.SWT.error(SWT.java:3643)
at org.eclipse.swt.SWT.error(SWT.java:3614)
at org.eclipse.swt.widgets.Dialog.checkParent(Dialoog.java:292)
at org.eclipse.swt.widgets.Dialog.<init>(Dialog.java:115)
at org.pentaho.di.ui.core.dialog.ErrorDialog.<init>(ErrorDialog.java:97)
at org.pentaho.di.ui.core.database.dialog.XulDatabaseDialog.createDialog(XullDatabaseDialog.java:159)
at org.pentaho.di.ui.core.database.dialog.XulDatabaseDialog.open(XulDatabaseDialog.java:1105)
at org.pentaho.di.ui.core.database.dialog.DatabaseDialog.open(DatabaseDialog.java:60)
at org.pentaho.di.ui.trans.step.BaseSteppDialog.showDbDialogUnlessCancelledOrValid(BaseStepDialog.java:776)
at org.pentaho.di.ui.trans.step.BaseStepDialog_ConnectionLine_Test.showDbDialog_LoopsUntilUniqueValueIsInput(BaseStepDialog_ConnectionLine_Test.java:245)
	0.009
```

**Comment by HiromuHota** [comment]
Resolved by df36fb969c858341d10fadfcb24086a919c27b88.
