### ISSUE TITLE
Stop button remains disabled even when failing to execute a trans in Spark

### ISSUE THREAD

**Issue by HiromuHota** [HiromuHota/pentaho-kettle#59]
A user can only click the "Run" button, but fails.
![screen shot 2017-06-12 at 4 10 32 pm](https://user-images.githubusercontent.com/20668349/27059989-c4d7cce8-4f8e-11e7-8ee5-635b40ee2535.png)

This can be seen as a regression caused by 487013eca510da6e232022500b86cb46e7b279a6.
But the root cause is that Exceptions caused by `trans.startThreads();` in `org.pentaho.di.ui.spoon.trans.TransGraph.startThreads()` are only handled when they are `KettleException`.
Since 7.1, it seems that `trans.startThreads();` can cause other exceptions like below and they should be properly handled.
```
2017/06/12 16:42:39 - Spoon - Using execution engine org.pentaho.di.engine.remote.client.RemoteClientEngine
2017/06/12 16:42:40 - Spoon - Transformation opened.
2017/06/12 16:42:40 - Spoon - Launching transformation [Untitled]...
2017/06/12 16:42:40 - Spoon - Started the transformation execution.
java.net.SocketException: Invalid argument
        at sun.nio.ch.Net.setIntOption0(Native Method)
        at sun.nio.ch.Net.setSocketOption(Net.java:334)
        at sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:190)
        at sun.nio.ch.SocketAdaptor.setIntOption(SocketAdaptor.java:281)
        at sun.nio.ch.SocketAdaptor.setReceiveBufferSize(SocketAdaptor.java:362)
        at org.apache.aries.rsa.provider.fastbin.tcp.LengthPrefixedCodec.setReadableByteChannel(LengthPrefixedCodec.java:125)
        at org.apache.aries.rsa.provider.fastbin.tcp.TcpTransport.initializeCodec(TcpTransport.java:166)
        at org.apache.aries.rsa.provider.fastbin.tcp.TcpTransport.setProtocolCodec(TcpTransport.java:485)
        at org.apache.aries.rsa.provider.fastbin.tcp.TransportPool.startNewTransport(TransportPool.java:172)
        at org.apache.aries.rsa.provider.fastbin.tcp.TransportPool.getIdleTransport(TransportPool.java:115)
        at org.apache.aries.rsa.provider.fastbin.tcp.TransportPool$1.run(TransportPool.java:89)
        at org.fusesource.hawtdispatch.TaskWrapper.run(TaskWrapper.java:22)
        at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
        at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)
java.net.SocketException: Invalid argument
        at sun.nio.ch.Net.setIntOption0(Native Method)
        at sun.nio.ch.Net.setSocketOption(Net.java:334)
        at sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:190)
        at sun.nio.ch.SocketAdaptor.setIntOption(SocketAdaptor.java:281)
        at sun.nio.ch.SocketAdaptor.setSendBufferSize(SocketAdaptor.java:351)
        at org.apache.aries.rsa.provider.fastbin.tcp.LengthPrefixedCodec.setWritableByteChannel(LengthPrefixedCodec.java:67)
        at org.apache.aries.rsa.provider.fastbin.tcp.TcpTransport.initializeCodec(TcpTransport.java:167)
        at org.apache.aries.rsa.provider.fastbin.tcp.TcpTransport.setProtocolCodec(TcpTransport.java:485)
        at org.apache.aries.rsa.provider.fastbin.tcp.TransportPool.startNewTransport(TransportPool.java:172)
        at org.apache.aries.rsa.provider.fastbin.tcp.TransportPool.getIdleTransport(TransportPool.java:115)
        at org.apache.aries.rsa.provider.fastbin.tcp.TransportPool$1.run(TransportPool.java:89)
        at org.fusesource.hawtdispatch.TaskWrapper.run(TaskWrapper.java:22)
        at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
        at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)
```

**Comment by HiromuHota** [comment]
Resolved by a58830ef038b9df06951e7d4b9a7d0e6bf3c1cee.
