### ISSUE TITLE
"Test Data Service" in "Data Service" dialog causes an error

### ISSUE THREAD

**Issue by HiromuHota** [HiromuHota/pentaho-kettle#67]
```
java.lang.IllegalArgumentException: Argument not valid
  at org.eclipse.swt.SWT.error(SWT.java:3794)
  at org.eclipse.swt.SWT.error(SWT.java:3731)
  at org.eclipse.swt.SWT.error(SWT.java:3702)
  at org.eclipse.swt.graphics.Image.<init>(Image.java:403)
  at org.pentaho.di.trans.dataservice.ui.DataServiceTestMetrics.refreshImage(DataServiceTestMetrics.java:131)
  at org.pentaho.di.trans.dataservice.ui.DataServiceTestMetrics.access$100(DataServiceTestMetrics.java:54)
  at org.pentaho.di.trans.dataservice.ui.DataServiceTestMetrics$3.paintControl(DataServiceTestMetrics.java:88)
  at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
  at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
  at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
  at org.eclipse.swt.widgets.Canvas.repaint(Canvas.java:193)
  at org.eclipse.swt.widgets.Canvas.notifyResize(Canvas.java:164)
  at org.eclipse.swt.widgets.Control.setBounds(Control.java:2543)
  at org.eclipse.swt.widgets.Control.setBounds(Control.java:901)
  at org.eclipse.swt.widgets.Control.setSize(Control.java:1015)
  at org.eclipse.swt.widgets.Control.setSize(Control.java:1035)
  at org.eclipse.rap.rwt.internal.textsize.EnlargeScrolledCompositeContentVisitor.enlargeContentControl(EnlargeScrolledCompositeContentVisitor.java:39)
  at org.eclipse.rap.rwt.internal.textsize.EnlargeScrolledCompositeContentVisitor.enlargeContentControl(EnlargeScrolledCompositeContentVisitor.java:32)
  at org.eclipse.rap.rwt.internal.textsize.EnlargeScrolledCompositeContentVisitor.visit(EnlargeScrolledCompositeContentVisitor.java:26)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.accept(WidgetTreeUtil.java:32)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.handleChildren(WidgetTreeUtil.java:111)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.accept(WidgetTreeUtil.java:40)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.handleChildren(WidgetTreeUtil.java:111)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.accept(WidgetTreeUtil.java:40)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.handleChildren(WidgetTreeUtil.java:111)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.accept(WidgetTreeUtil.java:40)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.handleChildren(WidgetTreeUtil.java:111)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.accept(WidgetTreeUtil.java:40)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.handleChildren(WidgetTreeUtil.java:111)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.accept(WidgetTreeUtil.java:40)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.handleChildren(WidgetTreeUtil.java:111)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.accept(WidgetTreeUtil.java:40)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.handleChildren(WidgetTreeUtil.java:111)
  at org.eclipse.swt.internal.widgets.WidgetTreeUtil.accept(WidgetTreeUtil.java:40)
  at org.eclipse.rap.rwt.internal.textsize.TextSizeRecalculation.enlargeScrolledCompositeContent(TextSizeRecalculation.java:72)
  at org.eclipse.rap.rwt.internal.textsize.TextSizeRecalculation.forceShellRecalculations(TextSizeRecalculation.java:46)
  at org.eclipse.rap.rwt.internal.textsize.TextSizeRecalculation.execute(TextSizeRecalculation.java:35)
  at org.eclipse.rap.rwt.internal.textsize.MeasurementOperator$MeasurementOperatorHandler$1.run(MeasurementOperator.java:127)
  at org.eclipse.rap.rwt.internal.lifecycle.ProcessActionRunner.executeNext(ProcessActionRunner.java:50)
  at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1196)
  at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
  at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
  at org.eclipse.jface.window.Window.runEventLoop(Window.java:869)
  at org.eclipse.jface.window.Window.open(Window.java:845)
  at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:80)
  at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:47)
  at org.pentaho.di.trans.dataservice.ui.DataServiceTestDialog.open(DataServiceTestDialog.java:127)
  at org.pentaho.di.trans.dataservice.ui.DataServiceDelegate.showTestDataServiceDialog(DataServiceDelegate.java:215)
  at org.pentaho.di.trans.dataservice.ui.controller.DataServiceDialogController.showTestDialog(DataServiceDialogController.java:82)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:313)
  at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:157)
  at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:141)
  at org.pentaho.ui.xul.swt.tags.SwtButton.access$500(SwtButton.java:43)
  at org.pentaho.ui.xul.swt.tags.SwtButton$4.widgetSelected(SwtButton.java:137)
  at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:263)
  at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
  at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
  at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
  at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
  at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
  at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
  at org.eclipse.jface.window.Window.runEventLoop(Window.java:869)
  at org.eclipse.jface.window.Window.open(Window.java:845)
  at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:80)
  at org.pentaho.di.ui.xul.KettleDialog.show(KettleDialog.java:47)
  at org.pentaho.di.trans.dataservice.ui.controller.DataServiceDialogController.open(DataServiceDialogController.java:112)
  at org.pentaho.di.trans.dataservice.ui.DataServiceDialog.open(DataServiceDialog.java:139)
  at org.pentaho.di.trans.dataservice.ui.DataServiceDelegate.createNewDataService(DataServiceDelegate.java:101)
  at org.pentaho.di.trans.dataservice.ui.menu.DataServiceStepHandler.newDataService(DataServiceStepHandler.java:55)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:313)
  at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:157)
  at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:141)
  at org.pentaho.ui.xul.jface.tags.JfaceMenuitem.access$100(JfaceMenuitem.java:43)
  at org.pentaho.ui.xul.jface.tags.JfaceMenuitem$1.run(JfaceMenuitem.java:106)
  at org.eclipse.jface.action.Action.runWithEvent(Action.java:493)
  at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:575)
  at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:492)
  at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:403)
  at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
  at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
  at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
  at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
  at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
  at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
  at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
  at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
  at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
  at java.lang.Thread.run(Thread.java:745)
  at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
```

**Comment by HiromuHota** [comment]
Resolved by HiromuHota/pdi-dataservice-server-plugin@59fe9753eba473df586b7ac92dd689ac79c9d912.
