### ISSUE TITLE
Cannot execute a trans (when deployed to Docker and connected to a Pentaho Repository)

### ISSUE THREAD

**Issue by HiromuHota** [HiromuHota/pentaho-kettle#77]
How to reproduce
1. Deploy webSpoon as a Docker container
2. Connect to a Pentaho Repository (running on the Docker host, so not on localhost)
3. Create a trans and save it to the repository
4. Run

Workaround:
- Deploy webSpoon in a non-Docker env, or
- Do not use Pentaho Repository

Here is the environment
OS: macOS 10.12.6
Docker: 17.06.0-ce
Docker image: hiromuhota/webspoon:0.7.1.12-full

Here are the error messages of the Docker container:
```
2017/08/23 17:43:36 - Spoon - Using legacy execution engine
2017/08/23 17:43:36 - Spoon - Transformation opened.
2017/08/23 17:43:36 - Spoon - Launching transformation [Transformation 1]...
2017/08/23 17:43:36 - Spoon - Started the transformation execution.
2017/08/23 17:43:36 - Transformation 1 - Dispatching started for transformation [Transformation 1]
2017/08/23 17:43:36 - Spoon - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Transformation 1: preparing transformation execution failed
2017/08/23 17:43:36 - Spoon - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : org.pentaho.di.core.exception.KettleTransException: 
2017/08/23 17:43:36 - Spoon - There was an error calculating the change data capture date range, it probably involved log table null.
2017/08/23 17:43:36 - Spoon - 
2017/08/23 17:43:36 - Spoon - No log table has been defined for the transformation.
2017/08/23 17:43:36 - Spoon - 
2017/08/23 17:43:36 - Spoon - 
2017/08/23 17:43:36 - Spoon - 	at org.pentaho.di.trans.Trans.calculateBatchIdAndDateRange(Trans.java:2238)
2017/08/23 17:43:36 - Spoon - 	at org.pentaho.di.trans.Trans.prepareExecution(Trans.java:985)
2017/08/23 17:43:36 - Spoon - 	at org.pentaho.di.ui.spoon.trans.TransGraph$26.run(TransGraph.java:4287)
2017/08/23 17:43:36 - Spoon - 	at java.lang.Thread.run(Thread.java:745)
2017/08/23 17:43:36 - Spoon - Caused by: org.pentaho.di.core.exception.KettleTransException: 
2017/08/23 17:43:36 - Spoon - No log table has been defined for the transformation.
2017/08/23 17:43:36 - Spoon - 
2017/08/23 17:43:36 - Spoon - 	at org.pentaho.di.trans.Trans.calculateBatchIdAndDateRange(Trans.java:2051)
2017/08/23 17:43:36 - Spoon - 	... 3 more
```

**Comment by HiromuHota** [comment]
Irrelevant.
This was not an issue of webSpoon, but a miss-configuration of logging.
