### ISSUE TITLE
Error in Web Spoon Deploying

### ISSUE THREAD

**Issue by nazeri84** [HiromuHota/pentaho-kettle#81]
I am trying to deploy webspoon on the linux (CentOS 7) by using tomcat, but I have faced following error. I should say before this, I deployed webspoon on the windows 10 and everything was ok!
in addition I have changed several libraries with new version of them (based on your notes in other issues),but the problem is still existing.
Please guide me what should I do to fix this problem.
![capture](https://user-images.githubusercontent.com/6742746/30777054-ca8acda0-a0b2-11e7-9084-f5f6a449c244.JPG)

**Comment by HiromuHota** [comment]
The error happened at Spoon.java:784, where opening a local metastore ($HOME/.pentaho/metastore).
Please check the owner/permission of $HOME/.pentaho (should be writable by the user who runs the Tomcat).

It tried to open the error dialog, but failed to do so.
Can you replace the `webapps/spoon/WEB-INF/lib/kettle-ui-swt-7.1.0.0-12-12.jar` with [this patched one](https://github.com/HiromuHota/pentaho-kettle/files/1330316/kettle-ui-swt-7.1.0.0-12-12.jar.zip) (please unzip it first) and try again?
The jar was patched so that error messages will be written in `logs/catalina.out` like below.

```
25-Sep-2017 17:32:13.580 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
25-Sep-2017 17:32:13.696 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
25-Sep-2017 17:32:13.698 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 121788 ms
2017/09/25 17:33:18 - Spoon - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Unable to open local Pentaho Metastore
2017/09/25 17:33:18 - Spoon - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : org.pentaho.metastore.api.exceptions.MetaStoreException: Unable to create XML meta store root folder: /home/vagrant/.pentaho/metastore
2017/09/25 17:33:18 - Spoon -   at org.pentaho.metastore.stores.xml.XmlMetaStore.<init>(XmlMetaStore.java:67)
2017/09/25 17:33:18 - Spoon -   at org.pentaho.metastore.stores.xml.XmlMetaStore.<init>(XmlMetaStore.java:58)
2017/09/25 17:33:18 - Spoon -   at org.pentaho.di.metastore.MetaStoreConst.openLocalPentahoMetaStore(MetaStoreConst.java:84)
2017/09/25 17:33:18 - Spoon -   at org.pentaho.di.metastore.MetaStoreConst.openLocalPentahoMetaStore(MetaStoreConst.java:61)
2017/09/25 17:33:18 - Spoon -   at org.pentaho.di.ui.spoon.Spoon.<init>(Spoon.java:776)
2017/09/25 17:33:18 - Spoon -   at org.pentaho.di.ui.spoon.Spoon.<init>(Spoon.java:762)
2017/09/25 17:33:18 - Spoon -   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2017/09/25 17:33:18 - Spoon -   at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
2017/09/25 17:33:18 - Spoon -   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
2017/09/25 17:33:18 - Spoon -   at java.lang.reflect.Constructor.newInstance(Unknown Source)
2017/09/25 17:33:18 - Spoon -   at org.eclipse.rap.rwt.internal.util.ClassUtil.createInstance(ClassUtil.java:57)
2017/09/25 17:33:18 - Spoon -   at org.eclipse.rap.rwt.internal.util.ClassUtil.newInstance(ClassUtil.java:38)
2017/09/25 17:33:18 - Spoon -   at org.eclipse.rap.rwt.internal.util.ClassUtil.newInstance(ClassUtil.java:32)
2017/09/25 17:33:18 - Spoon -   at org.eclipse.rap.rwt.internal.SingletonManager.getSingleton(SingletonManager.java:46)
2017/09/25 17:33:18 - Spoon -   at org.eclipse.rap.rwt.SingletonUtil.getUniqueInstance(SingletonUtil.java:74)
2017/09/25 17:33:18 - Spoon -   at org.eclipse.rap.rwt.SingletonUtil.getSessionInstance(SingletonUtil.java:58)
2017/09/25 17:33:18 - Spoon -   at org.pentaho.di.ui.spoon.Spoon.getInstance(Spoon.java:1084)
2017/09/25 17:33:18 - Spoon -   at org.pentaho.di.ui.spoon.WebSpoonEntryPoint.createContents(WebSpoonEntryPoint.java:72)
2017/09/25 17:33:18 - Spoon -   at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:60)
2017/09/25 17:33:18 - Spoon -   at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
2017/09/25 17:33:18 - Spoon -   at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
2017/09/25 17:33:18 - Spoon -   at java.lang.Thread.run(Unknown Source)
2017/09/25 17:33:18 - Spoon -   at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
```

The above error was caused by changing the owner of `$HOME/.pentaho/` and making it un-writable.
I tested with the following environment:
OS: CentOS 7 (vagrant image centos/7)
Java: Oracle 8u144
Servlet container: Apache Tomcat 8.5.20
webSpoon: 0.7.1.12

**Comment by nazeri84** [comment]
I changed the permissions and now my webspoon is working without any problem.
thank you so much for your help.

**Comment by HiromuHota** [comment]
Glad to hear that
