### ISSUE TITLE
Carte bypasses the permission checks

### ISSUE THREAD

**Issue by HiromuHota** [HiromuHota/pentaho-kettle#95]
When the custom security manager is enabled as explained [here](https://github.com/HiromuHota/pentaho-kettle/wiki/Admin%3A-Security#file-access-control-by-a-custom-security-manager-experimental), file access from trans/job entry is restricted to `$HOME/.kettle/users/$username` and `$HOME/.pentaho/users/$username`.
However, running the trans/job entry from Carte bypasses the permission checks.

How to reproduce
1. Enable the custom security manager
2. Create a trans with "Generate random value" and "Text file output" (filename: anywhere outside of the permitted directory)
3. Run the trans from webSpoon (will fail)
4. Create a slave server and a run configuration for this slave server
5. Run the same trans in Carte

This is an expected error message for the step 3.
```
2018/02/05 22:23:17 - Untitled - Dispatching started for transformation [Untitled]
2018/02/05 22:23:17 - Text file output.0 - ERROR (version 8.0.0.0-28-13, build 8.0.0.0-28-13 from 2018-02-03 12.06.16 by jenkins) : Couldn't open file file:///root/.kettle/file.csv
2018/02/05 22:23:17 - Text file output.0 - ERROR (version 8.0.0.0-28-13, build 8.0.0.0-28-13 from 2018-02-03 12.06.16 by jenkins) : org.pentaho.di.core.exception.KettleException: 
2018/02/05 22:23:17 - Text file output.0 - Error opening new file : org.apache.commons.vfs2.FileSystemException: Could not determine the type of file "file:///root/.kettle".
2018/02/05 22:23:17 - Text file output.0 - 
2018/02/05 22:23:17 - Text file output.0 - 	at org.pentaho.di.trans.steps.textfileoutput.TextFileOutput.openNewFile(TextFileOutput.java:692)
2018/02/05 22:23:17 - Text file output.0 - 	at org.pentaho.di.trans.steps.textfileoutput.TextFileOutput.init(TextFileOutput.java:802)
2018/02/05 22:23:17 - Text file output.0 - 	at org.pentaho.di.trans.step.StepInitThread.run(StepInitThread.java:69)
2018/02/05 22:23:17 - Text file output.0 - 	at java.lang.Thread.run(Thread.java:748)
2018/02/05 22:23:17 - Generate random value.0 - Finished processing (I=0, O=0, R=1, W=0, U=0, E=0)
2018/02/05 22:23:18 - Text file output.0 - Finished processing (I=0, O=0, R=0, W=0, U=0, E=1)
2018/02/05 22:23:18 - Untitled - ERROR (version 8.0.0.0-28-13, build 8.0.0.0-28-13 from 2018-02-03 12.06.16 by jenkins) : Errors detected!
2018/02/05 22:23:18 - Untitled - ERROR (version 8.0.0.0-28-13, build 8.0.0.0-28-13 from 2018-02-03 12.06.16 by jenkins) : Errors detected!
2018/02/05 22:23:18 - Untitled - ERROR (version 8.0.0.0-28-13, build 8.0.0.0-28-13 from 2018-02-03 12.06.16 by jenkins) : Errors detected!
2018/02/05 22:23:18 - Untitled - Transformation detected one or more steps with errors.
2018/02/05 22:23:18 - Untitled - Transformation is killing the other steps!
```

**Comment by HiromuHota** [comment]
Resolved by 1347de8b80435e1e392b6477dc3080cd5d7dc7bf.
